---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for Selenium hub

Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair for SSH access to the EC2 instance.
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  SeleniumHubSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'SeleniumHub-${AWS::StackName}'
      GroupDescription: Enable access to Selenium hub and SSH
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '4444'
        ToPort: '4444'
        CidrIp: 0.0.0.0/0
      
  SeleniumHub:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install Docker and launch SeleniumHub
      AWS::CloudFormation::Init:
        config:
          packages:
            apt:
              apt-transport-https: []
              ca-certificates: []
              curl: []
              software-properties-common: []
          files:
            "/etc/apt/sources.list.d/docker.list":
              content: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.SeleniumHub.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource SeleniumHub --region ${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"
          commands:
            a_cert:
              command: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -"
            b_apt_update:
              command: "apt-get update"
            c_docker:
              command: "apt-get install -y docker-ce"
            d_run_selenium:
              command: "docker run -d -p 4444:4444 --restart always --name selenium-hub selenium/hub"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Properties:
      ImageId: ami-8fd760f6
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SeleniumHubSecurityGroup
      Tags:
        - Key: "Name"
          Value: !Sub "SeleniumHub-${AWS::StackName}"
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash -xe
            apt-get update
            apt-get -y install python-setuptools
            easy_install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
            # Start cfn-init
            /usr/local/bin/cfn-init -s ${AWS::StackId} -r SeleniumHub --region ${AWS::Region}
            /usr/local/bin/cfn-hup
            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource SeleniumHub --region ${AWS::Region}

Outputs:
  PublicIp:
    Description: Instance Public IP
    Value: !GetAtt SeleniumHub.PublicIp
    Export:
      Name: SeleniumHubPublicIP
  SeleniumHubEndpoint:
    Description: URL to Selenium hub
    Value: !Sub |
      http://${SeleniumHub.PublicDnsName}:4444/grid/console